#  Pandas: Tabular Data
### learning objectives 
● Load a real dataset into a DataFrame and inspect its structure.

● Select columns and filter rows by condition.

● Clean missing values and duplicates, and aggregate data with groupby.

### Key Topics
● Series vs. DataFrame

● Loading and inspecting data: read_csv, head, info, describe

● Selecting and filtering: columns, boolean filtering, .loc/.iloc

● Cleaning: missing values, duplicates, type conversion

● Grouping and aggregation: groupby, agg (split-apply-combine)

Pandas is the main library for tabular data. A Series is one labeled column, while a DataFrame is a full table of rows and named columns — the format most datasets use (CSV, Excel, SQL).


## 1. Loading and inspecting Data
Always start by loading the dataset and inspecting its shape, columns, data types, and a few sample rows.

In [35]:
import pandas as pd

df =pd.read_csv("student_data.csv")
df.head() #show the first 5 rows

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18.0,U,GT3,A,4.0,4.0,at_home,teacher,...,4.0,3.0,4.0,1.0,1.0,3.0,6.0,5,6.0,6.0
1,GP,F,17.0,U,GT3,T,1.0,1.0,at_home,other,...,5.0,3.0,3.0,1.0,1.0,3.0,4.0,5,5.0,6.0
2,GP,F,15.0,U,LE3,T,1.0,1.0,at_home,other,...,4.0,3.0,2.0,2.0,3.0,3.0,10.0,7,8.0,10.0
3,GP,F,15.0,U,GT3,T,4.0,2.0,health,services,...,3.0,2.0,2.0,1.0,1.0,5.0,2.0,15,14.0,15.0
4,GP,F,16.0,U,GT3,T,3.0,3.0,other,other,...,4.0,3.0,2.0,1.0,2.0,5.0,4.0,6,10.0,10.0

In [36]:
df.tail() #the last five col.

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
415,NaN,M,15.0,U,GT3,T,4.0,4.0,teacher,health,...,3.0,2.0,2.0,1.0,NaN,5.0,NaN,14,15.0,15.0
416,MS,F,18.0,R,GT3,T,NaN,4.0,other,teacher,...,3.0,2.0,2.0,4.0,2.0,5.0,10.0,14,12.0,NaN
417,NaN,M,17.0,R,GT3,T,2.0,2.0,services,NaN,...,NaN,4.0,5.0,5.0,5.0,4.0,8.0,11,10.0,10.0
418,GP,NaN,20.0,U,GT3,A,3.0,NaN,services,other,...,NaN,5.0,3.0,1.0,1.0,5.0,0.0,17,NaN,18.0
419,GP,F,18.0,NaN,GT3,NaN,1.0,1.0,at_home,other,...,5.0,2.0,5.0,1.0,5.0,4.0,6.0,9,8.0,10.0

In [37]:
df.shape #(number of rows,number of columns)

(420, 33)

In [38]:
df.info() # column names, non-null counts, dtypes

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      417 non-null    str
 1   sex         417 non-null    str
 2   age         417 non-null    float64
 3   address     418 non-null    str
 4   famsize     416 non-null    str
 5   Pstatus     416 non-null    str
 6   Medu        415 non-null    float64
 7   Fedu        416 non-null    float64
 8   Mjob        419 non-null    str
 9   Fjob        417 non-null    str
 10  reason      414 non-null    str
 11  guardian    419 non-null    str
 12  traveltime  417 non-null    float64
 13  studytime   416 non-null    float64
 14  failures    415 non-null    float64
 15  schoolsup   417 non-null    str
 16  famsup      415 non-null    str
 17  paid        417 non-null    str
 18  activities  419 non-null    str
 19  nursery     419 non-null    str
 20  higher      418 non-null    str
 21  internet    417 non-null    str
 22  romantic    418 non-null    str
 23  famrel      416 non-null    float64
 24  freetime    417 non-null    float64
 25  goout       418 non-null    float64
 26  Dalc        419 non-null    float64
 27  Walc        416 non-null    float64
 28  health      419 non-null    float64
 29  absences    416 non-null    float64
 30  G1          420 non-null    int64
 31  G2          417 non-null    float64
 32  G3          418 non-null    float64
dtypes: float64(15), int64(1), str(17)
memory usage: 108.4 KB

In [39]:
df.describe()  # summary statistics for numeric columns

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,417.000000,415.000000,416.000000,417.000000,416.000000,415.000000,416.000000,417.000000,418.000000,419.000000,416.000000,419.000000,416.000000,420.000000,417.000000,418.000000
mean,16.688249,2.749398,2.536058,1.458034,2.031250,0.332530,3.930288,3.213429,3.107656,1.491647,2.302885,3.563246,5.713942,10.916667,10.726619,10.430622
std,1.279904,1.094494,1.090439,0.716421,0.848235,0.745536,0.906441,1.002407,1.125415,0.915994,1.302302,1.382628,7.863130,3.311974,3.733565,4.586104
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.500000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.250000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

## 2. Selection and Filtering
Select columns by name, and rows by condition (boolean filtering) — the Pandas equivalent of NumPy's boolean 
masking. .loc selects by label, .iloc by integer position.


* column selection
   * single col(series)  : df["col name"]
   * multi col (dtatframe) : df[["col1","col2",...,"coln"]]
* row selection
   * by condition : df[df['row']>x]
   * by label : df.loc[index], df.loc[row index,'col name'] for specific cell

In [40]:
df["age"]

0      18.0
1      17.0
2      15.0
3      15.0
4      16.0
       ...
415    15.0
416    18.0
417    17.0
418    20.0
419    18.0
Name: age, Length: 420, dtype: float64

In [41]:
df[["school","studytime"]]

    school  studytime
0       GP        2.0
1       GP        2.0
2       GP        2.0
3       GP        3.0
4       GP        2.0
..     ...        ...
415    NaN        2.0
416     MS        2.0
417    NaN        1.0
418     GP        1.0
419     GP        1.0

[420 rows x 2 columns]

In [42]:
df[df["age"]>15]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18.0,U,GT3,A,4.0,4.0,at_home,teacher,...,4.0,3.0,4.0,1.0,1.0,3.0,6.0,5,6.0,6.0
1,GP,F,17.0,U,GT3,T,1.0,1.0,at_home,other,...,5.0,3.0,3.0,1.0,1.0,3.0,4.0,5,5.0,6.0
4,GP,F,16.0,U,GT3,T,3.0,3.0,other,other,...,4.0,3.0,2.0,1.0,2.0,5.0,4.0,6,10.0,10.0
5,GP,M,16.0,U,LE3,T,4.0,3.0,services,other,...,5.0,4.0,2.0,1.0,2.0,5.0,10.0,15,15.0,15.0
6,GP,M,16.0,U,LE3,T,2.0,2.0,other,other,...,4.0,4.0,4.0,1.0,1.0,3.0,0.0,12,12.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,GP,F,18.0,U,GT3,T,1.0,NaN,other,other,...,5.0,4.0,4.0,1.0,1.0,4.0,4.0,8,9.0,10.0
416,MS,F,18.0,R,GT3,T,NaN,4.0,other,teacher,...,3.0,2.0,2.0,4.0,2.0,5.0,10.0,14,12.0,NaN
417,NaN,M,17.0,R,GT3,T,2.0,2.0,services,NaN,...,NaN,4.0,5.0,5.0,5.0,4.0,8.0,11,10.0,10.0
418,GP,NaN,20.0,U,GT3,A,3.0,NaN,services,other,...,NaN,5.0,3.0,1.0,1.0,5.0,0.0,17,NaN,18.0
419,GP,F,18.0,NaN,GT3,NaN,1.0,1.0,at_home,other,...,5.0,2.0,5.0,1.0,5.0,4.0,6.0,9,8.0,10.0

In [43]:
df.loc[df["health"]>2,"Fjob"]

0       teacher
1         other
2         other
3      services
4         other
         ...
415      health
416     teacher
417         NaN
418       other
419       other
Name: Fjob, Length: 323, dtype: str

## 3. Cleaning Data
Real data is messy: missing values, duplicates, and wrong types are the norm. Cleaning is often the largest part of 
any ML project, and doing it correctly is what everything downstream depends on.

In [44]:
df.isnull().sum() # count missing values per column

school        3
sex           3
age           3
address       2
famsize       4
Pstatus       4
Medu          5
Fedu          4
Mjob          1
Fjob          3
reason        6
guardian      1
traveltime    3
studytime     4
failures      5
schoolsup     3
famsup        5
paid          3
activities    1
nursery       1
higher        2
internet      3
romantic      2
famrel        4
freetime      3
goout         2
Dalc          1
Walc          4
health        1
absences      4
G1            0
G2            3
G3            2
dtype: int64

In [45]:
df["age"] = df["age"].fillna(df["age"].mean())

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      417 non-null    str
 1   sex         417 non-null    str
 2   age         420 non-null    float64
 3   address     418 non-null    str
 4   famsize     416 non-null    str
 5   Pstatus     416 non-null    str
 6   Medu        415 non-null    float64
 7   Fedu        416 non-null    float64
 8   Mjob        419 non-null    str
 9   Fjob        417 non-null    str
 10  reason      414 non-null    str
 11  guardian    419 non-null    str
 12  traveltime  417 non-null    float64
 13  studytime   416 non-null    float64
 14  failures    415 non-null    float64
 15  schoolsup   417 non-null    str
 16  famsup      415 non-null    str
 17  paid        417 non-null    str
 18  activities  419 non-null    str
 19  nursery     419 non-null    str
 20  higher      418 non-null    str
 21  internet    417 non-null    str
 22  romantic    418 non-null    str
 23  famrel      416 non-null    float64
 24  freetime    417 non-null    float64
 25  goout       418 non-null    float64
 26  Dalc        419 non-null    float64
 27  Walc        416 non-null    float64
 28  health      419 non-null    float64
 29  absences    416 non-null    float64
 30  G1          420 non-null    int64
 31  G2          417 non-null    float64
 32  G3          418 non-null    float64
dtypes: float64(15), int64(1), str(17)
memory usage: 108.4 KB

In [47]:
df.drop_duplicates(inplace=True)

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      417 non-null    str
 1   sex         417 non-null    str
 2   age         420 non-null    float64
 3   address     418 non-null    str
 4   famsize     416 non-null    str
 5   Pstatus     416 non-null    str
 6   Medu        415 non-null    float64
 7   Fedu        416 non-null    float64
 8   Mjob        419 non-null    str
 9   Fjob        417 non-null    str
 10  reason      414 non-null    str
 11  guardian    419 non-null    str
 12  traveltime  417 non-null    float64
 13  studytime   416 non-null    float64
 14  failures    415 non-null    float64
 15  schoolsup   417 non-null    str
 16  famsup      415 non-null    str
 17  paid        417 non-null    str
 18  activities  419 non-null    str
 19  nursery     419 non-null    str
 20  higher      418 non-null    str
 21  internet    417 non-null    str
 22  romantic    418 non-null    str
 23  famrel      416 non-null    float64
 24  freetime    417 non-null    float64
 25  goout       418 non-null    float64
 26  Dalc        419 non-null    float64
 27  Walc        416 non-null    float64
 28  health      419 non-null    float64
 29  absences    416 non-null    float64
 30  G1          420 non-null    int64
 31  G2          417 non-null    float64
 32  G3          418 non-null    float64
dtypes: float64(15), int64(1), str(17)
memory usage: 108.4 KB

In [49]:
at_risk = df[df["failures"] > 0]
at_risk[["G1","G2","G3","absences","studytime"]].describe()

              G1         G2         G3   absences  studytime
count  86.000000  86.000000  86.000000  85.000000  85.000000
mean    8.767442   8.325581   7.209302   7.823529   1.776471
std     3.028004   3.312869   4.703231   8.802295   0.713417
min     3.000000   0.000000   0.000000   0.000000   1.000000
25%     6.250000   7.000000   4.250000   0.000000   1.000000
50%     8.000000   8.000000   8.000000   6.000000   2.000000
75%    10.750000  10.000000  10.000000  14.000000   2.000000
max    18.000000  18.000000  18.000000  40.000000   4.000000

## 4. Grouping and Aggregation

splits data by column values, applies an aggregation (mean, sum, count), and recombines — the “split‑apply‑combine” pattern that reveals group‑level insights.

In [50]:
df.groupby("school")["G3"].agg(["mean", "count"])

             mean  count
school
GP      10.508152    368
MS       9.744681     47

In [51]:
df.groupby("sex")[["studytime", "G3"]].agg(["mean", "count", "max"])

    studytime                    G3
         mean count  max       mean count   max
sex
F    2.263889   216  4.0   9.949541   218  19.0
M    1.786802   197  4.0  10.908629   197  20.0

## 5. Hands on Lab

   ● Step 1: Load a provided CSV dataset into a DataFrame and report its shape, columns, and dtypes.

   ● Step 2: Count missing values per column and handle them (fill or drop) with a documented justification.

   ● Step 3: Filter the data to a meaningful subset (e.g. rows above a threshold) and describe what you find.

   ● Step 4: Use groupby to compute an aggregate statistic per category and interpret the result in a Markdown cell.

In [52]:
#step1
import pandas as pd

df = pd.read_csv("train-selected-columns.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub

In [53]:
df.shape  # (rows, columns)

(1460, 10)

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           1460 non-null   int64
 1   MSSubClass   1460 non-null   int64
 2   MSZoning     1460 non-null   str
 3   LotFrontage  1201 non-null   float64
 4   LotArea      1460 non-null   int64
 5   Street       1460 non-null   str
 6   Alley        91 non-null     str
 7   LotShape     1460 non-null   str
 8   LandContour  1460 non-null   str
 9   Utilities    1460 non-null   str
dtypes: float64(1), int64(3), str(6)
memory usage: 114.2 KB

In [55]:
#step2
df.isnull().sum()

Id                0
MSSubClass        0
MSZoning          0
LotFrontage     259
LotArea           0
Street            0
Alley          1369
LotShape          0
LandContour       0
Utilities         0
dtype: int64

In [56]:
df.dropna(inplace=True)

In [57]:
df.info()

<class 'pandas.DataFrame'>
Index: 86 entries, 21 to 1454
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           86 non-null     int64
 1   MSSubClass   86 non-null     int64
 2   MSZoning     86 non-null     str
 3   LotFrontage  86 non-null     float64
 4   LotArea      86 non-null     int64
 5   Street       86 non-null     str
 6   Alley        86 non-null     str
 7   LotShape     86 non-null     str
 8   LandContour  86 non-null     str
 9   Utilities    86 non-null     str
dtypes: float64(1), int64(3), str(6)
memory usage: 7.4 KB

step3
Big lots tend to have more frontage, which makes sense — wider lots. Most of them are zoned RL (low-density residential) and aren't perfectly rectangular. So bigger lots aren't spread evenly across the market — they show up more in a certain type of neighborhood.

In [58]:
#step3

df["LotArea"] >df["LotArea"].mean()

21      False
30       True
56      False
79       True
87      False
        ...
1404     True
1414     True
1427     True
1432     True
1454    False
Name: LotArea, Length: 86, dtype: bool

In [59]:
#step4
df.groupby("MSZoning")[["LotArea", "LotFrontage"]].agg(["mean", "median", "count"])

               LotArea                LotFrontage
                  mean   median count        mean median count
MSZoning
C (all)    8606.000000   8606.0     2   58.000000   58.0     2
FV         4166.666667   3460.0    24   39.166667   34.5    24
RH         7698.000000   7698.0     2   57.500000   57.5     2
RL        10041.111111  10800.0    18   57.833333   60.0    18
RM         8483.825000   8980.0    40   62.750000   60.0    40